package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate mJoinPredicate;
    private DbIterator mChild1;
    private DbIterator mChild2;

    /**
     * This field is used for joining the tuples. It's possible that 
     * the first tuple iterated by mChild1 is shorter than the one
     * in mChild2, so we use this tuple to continue checking t1 against
     * t2 if we run out.
     */
    private Tuple curT1Tuple;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
	mJoinPredicate = p;
	mChild1 = child1;
	mChild2 = child2;
	curT1Tuple = null;
    }

    public JoinPredicate getJoinPredicate() {
	return mJoinPredicate;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
	TupleDesc td1 = mChild1.getTupleDesc();
	return td1.getFieldName(mJoinPredicate.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
	TupleDesc td2 = mChild2.getTupleDesc();
	return td2.getFieldName(mJoinPredicate.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
	return TupleDesc.merge(mChild1.getTupleDesc(), mChild2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
	super.open();
	mChild1.open();
	mChild2.open();
    }

    public void close() {
	super.close();
	mChild1.close();
	mChild2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
	mChild1.rewind();
	mChild2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
	while( (curT1Tuple != null) || mChild1.hasNext() ) {
	    Tuple t1Tuple;
	    if (curT1Tuple != null)
		t1Tuple = curT1Tuple;
	    else {
		curT1Tuple = mChild1.next();
		t1Tuple = curT1Tuple;
	    }

	    while(mChild2.hasNext()) {
		Tuple t2Tuple = mChild2.next();
		if (mJoinPredicate.filter(t1Tuple, t2Tuple))
		    return joinTuples(t1Tuple, t2Tuple);
	    }
	    
	    // If we reach here, we need to rewind child2 and start fresh
	    curT1Tuple = null;
	    mChild2.rewind();
	}
	return null;
    }

    private Tuple joinTuples(Tuple t1, Tuple t2) {
	System.out.println("Tuple 1: " + t1.toString());
	System.out.println("Tuple 2: " + t2.toString());

	TupleDesc td1 = t1.getTupleDesc();
	TupleDesc td2 = t2.getTupleDesc();
	TupleDesc joinedTd = TupleDesc.merge(td1, td2);
	Tuple retTuple = new Tuple(joinedTd);

	//Get fields from tuples
	int nFields1 = td1.numFields();
	int nFields2 = td2.numFields();
	for (int i = 0; i < nFields1; i++)
	    retTuple.setField(i, t1.getField(i));
	for (int i = nFields1; i < nFields1 + nFields2; i++)
	    retTuple.setField(i, t2.getField(i - nFields1));
	
	System.out.println("Joined tuple: " + retTuple.toString());
	return retTuple;
    }

    @Override
    public DbIterator[] getChildren() {
	return new DbIterator[]{mChild1, mChild2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
	mChild1 = children[0];
	mChild2 = children[1];
    }

}
